# Generated by Django 4.2.6 on 2023-10-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SmallIntegerField(blank=True, default=0, verbose_name='شناسه ی نود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
            ],
            options={
                'verbose_name': 'نود برد',
                'verbose_name_plural': 'نود های برد',
            },
        ),
        migrations.CreateModel(
            name='BoardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تام برد')),
                ('is_input', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
            ],
            options={
                'verbose_name': 'برد',
                'verbose_name_plural': 'برد ها',
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تام برد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_input', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
            ],
            options={
                'verbose_name': 'نود',
                'verbose_name_plural': 'نود ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تام پروژه')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس محل سکونت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام اتاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_room', to='project.project', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectBoards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='تام برد')),
                ('unique_id', models.SmallIntegerField(blank=True, default=0, verbose_name='شناسه ی برد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='project.boardtype', verbose_name='برد مربوطه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.project', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'برد پروژه',
                'verbose_name_plural': 'برد های پروژه',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تجهیز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('board_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_node', to='project.boardnodes', verbose_name='برد')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='project.room', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
            },
        ),
        migrations.AddField(
            model_name='boardnodes',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='project.nodetype', verbose_name='نود مربوطه'),
        ),
        migrations.AddField(
            model_name='boardnodes',
            name='project_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='project.projectboards', verbose_name='برد مربوطه'),
        ),
    ]
