# Generated by Django 4.2.6 on 2023-11-03 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardnodes',
            old_name='project_board',
            new_name='board_project',
        ),
        migrations.AddField(
            model_name='boardnodes',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن نود'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('0', 'کلید 3 تایمر'), ('1', 'کلید تک تایمر'), ('2', 'سنسور دما'), ('3', 'سنسور گاز'), ('4', 'سنسور رطوبت'), ('5', 'سنسور خاک'), ('6', 'چشمی ها و سنسور تشخیص حرکت'), ('7', 'دیمر ها')], default='0', max_length=1, verbose_name='نوع تجهیز'),
        ),
        migrations.AddField(
            model_name='projectboards',
            name='parent_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_board', to='project.projectboards', verbose_name='برد مربوطه'),
        ),
        migrations.CreateModel(
            name='ProjectScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_scenario', to='project.device', verbose_name='تجهیز سناریو')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_scenario', to='project.project', verbose_name='پروژه ی سناریو')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms_scenario', to='project.room', verbose_name='اتاق سناریو')),
            ],
            options={
                'verbose_name': 'سناریو',
                'verbose_name_plural': 'سناریو ها',
            },
        ),
    ]
