# Generated by Django 4.2.6 on 2023-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_project_board_boardnodes_board_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtype',
            name='name',
            field=models.CharField(default='0', max_length=1, verbose_name='تام برد'),
        ),
        migrations.AlterField(
            model_name='projectboards',
            name='board_type',
            field=models.CharField(choices=[('0', 'برد پیامکی'), ('1', 'برد وای فای'), ('2', 'برد سنسور'), ('3', 'برد رله'), ('4', 'برد دیمر')], default='0', max_length=1, verbose_name='تام برد'),
        ),
    ]
