# Generated by Django 4.2.6 on 2023-11-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_boardtype_name_alter_projectboards_board_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboards',
            name='parent_board',
        ),
        migrations.AddField(
            model_name='projectboards',
            name='parent_sms_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_board', to='project.projectboards', verbose_name='برد پیامکی مربوطه'),
        ),
        migrations.AddField(
            model_name='projectboards',
            name='parent_wifi_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_board', to='project.projectboards', verbose_name='برد وای فای مربوطه'),
        ),
        migrations.AlterField(
            model_name='boardtype',
            name='name',
            field=models.CharField(default='0', max_length=100, verbose_name='تام برد'),
        ),
        migrations.AlterField(
            model_name='projectboards',
            name='board_type',
            field=models.CharField(choices=[('0', 'برد پیامکی'), ('1', 'برد وای فای'), ('2', 'برد سنسور'), ('3', 'برد رله'), ('4', 'برد دیمر')], default='0', max_length=1, verbose_name='نام برد'),
        ),
        migrations.AlterField(
            model_name='projectboards',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام برد'),
        ),
    ]
