# Generated by Django 4.2.6 on 2023-11-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_projectboards_parent_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtype',
            name='name',
            field=models.CharField(choices=[('0', 'برد پیامکی'), ('1', 'برد وای فای'), ('2', 'برد سنسور'), ('3', 'برد رله'), ('4', 'برد دیمر')], default='0', max_length=1, verbose_name='نام برد'),
        ),
        migrations.AlterField(
            model_name='nodetype',
            name='name',
            field=models.CharField(choices=[('0', 'کلید تک تایمر'), ('1', 'سنسور دما'), ('2', 'سنسور رطوبت'), ('3', 'سنسور گاز'), ('4', 'سنسور خاک'), ('5', 'دیمر'), ('6', 'کلید سه تایمر'), ('7', 'چشمی ها و سنسور تشخیص حرکت')], max_length=1, verbose_name='نام نود'),
        ),
        migrations.AlterField(
            model_name='projectboards',
            name='board_type',
            field=models.CharField(default='0', max_length=1, verbose_name='نام برد'),
        ),
        migrations.CreateModel(
            name='NodeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.SmallIntegerField(blank=True, default=0, verbose_name='شناسه ی نود')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن نود')),
                ('board_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_project', to='project.projectboards', verbose_name='بردهای انتخابی')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='project.nodetype', verbose_name='نود ها')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_node', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'نود پروژه',
                'verbose_name_plural': 'نودهای پروژه',
            },
        ),
        migrations.AddField(
            model_name='projectboards',
            name='node',
            field=models.ManyToManyField(related_name='board_node', through='project.NodeProject', to='project.nodetype', verbose_name='نود های برد'),
        ),
        migrations.AlterField(
            model_name='device',
            name='board_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_node', to='project.nodeproject', verbose_name='نود'),
        ),
        migrations.DeleteModel(
            name='BoardNodes',
        ),
    ]
