# Generated by Django 4.2.6 on 2023-11-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_parent_sms_board_projectboards_control_sms_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='board_node',
        ),
        migrations.AddField(
            model_name='device',
            name='node_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='node_project', to='project.nodeproject', verbose_name='نود'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('0', 'کلید تک تایمر'), ('1', 'سنسور دما'), ('2', 'سنسور رطوبت'), ('3', 'سنسور گاز'), ('4', 'سنسور خاک'), ('5', 'دیمر'), ('6', 'کلید سه تایمر'), ('7', 'چشمی ها و سنسور تشخیص حرکت')], default='0', max_length=1, verbose_name='نوع تجهیز'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='project.room', verbose_name='اتاق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_room', to='project.project', verbose_name='اتاق'),
        ),
    ]
