# Generated by Django 4.2.6 on 2023-11-17 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_device_board_node_device_node_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='project_device', to='project.project', verbose_name='پروژه ی تجهیز'),
        ),
    ]
