# Generated by Django 4.2.6 on 2023-11-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_device_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='event_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='رویداد'),
        ),
        migrations.AlterField(
            model_name='projectscenario',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_scenario', to='project.device', verbose_name='تجهیز سناریو'),
        ),
        migrations.AlterField(
            model_name='projectscenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scenario', to='project.project', verbose_name='پروژه ی سناریو'),
        ),
        migrations.AlterField(
            model_name='projectscenario',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_scenario', to='project.room', verbose_name='اتاق سناریو'),
        ),
    ]
