# Generated by Django 4.2.6 on 2024-02-02 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_alter_device_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscenario',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectscenario',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectscenario',
            name='room',
        ),
        migrations.AddField(
            model_name='projectscenario',
            name='status',
            field=models.CharField(choices=[('0', 'خاموش'), ('1', 'روشن')], default='0', max_length=1, verbose_name='وضعیت سناریو'),
        ),
        migrations.AddField(
            model_name='projectscenario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_scenario', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectscenario',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_scenario', to='project.device', verbose_name='تجهیز'),
        ),
    ]
