# Generated by Django 4.2.6 on 2024-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_projectscenario_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscenario',
            name='type',
            field=models.CharField(blank=True, choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4')], max_length=1, null=True, verbose_name='نوع'),
        ),
    ]
