# Generated by Django 4.2.6 on 2024-02-05 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projectscenario_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscenario',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_scenario', to='project.project', verbose_name='پروژه'),
            preserve_default=False,
        ),
    ]
