# Generated by Django 4.2.6 on 2024-03-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_projectscenario_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectscenario',
            name='device',
        ),
        migrations.AddField(
            model_name='projectscenario',
            name='device',
            field=models.ManyToManyField(related_name='device_scenario', to='project.device', verbose_name='تجهیز'),
        ),
    ]
