# Generated by Django 4.2.6 on 2024-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_projectscenario_device_projectscenario_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscenario',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سناریو'),
        ),
    ]
