# Generated by Django 4.2.6 on 2024-03-23 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_projectscenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='project_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_device', to='project.projectboards', verbose_name='برد مرتبط'),
        ),
    ]
