# Generated by Django 4.2.6 on 2024-03-29 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_device_project_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeProject',
            new_name='Node',
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برد')),
                ('unique_id', models.SmallIntegerField(blank=True, default=1, verbose_name='شناسه ی برد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('delete_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ حذف')),
                ('board_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='project.boardtype', verbose_name='برد مربوطه')),
                ('control_sms_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_board', to='project.board', verbose_name='برد پیامکی مربوطه')),
                ('control_wifi_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_board', to='project.board', verbose_name='برد وای فای مربوطه')),
                ('node', models.ManyToManyField(related_name='board_node', through='project.Node', to='project.nodetype', verbose_name='نود های برد')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='project.project', verbose_name='پروژه مربوطه')),
            ],
            options={
                'verbose_name': 'برد پروژه',
                'verbose_name_plural': 'برد های پروژه',
            },
        ),
        migrations.AlterField(
            model_name='device',
            name='project_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_device', to='project.board', verbose_name='برد مرتبط'),
        ),
        migrations.AlterField(
            model_name='node',
            name='board_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_project', to='project.board', verbose_name='بردهای انتخابی'),
        ),
        migrations.DeleteModel(
            name='ProjectBoards',
        ),
    ]
